### ISSUE TITLE
EPIC: RW - Film

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-AMANDA-V7#20]
*In Progress*
_Epic_

**UAT Resource(s)**
- Evelyn

**Test Session Info:**
- [x] Scheduled
    - Date/Time: 12/23/2020
- [x] Updated card with UAT Notes

**Comment by Nadin-Nader** [comment]
Had the meeting with Evelyn to UAT AMANDA V7 RW - Film

**USERNAME: POWERSE**
**RSN: 2020 172605 000 00**
**Folder: 1258522**

- EVELYN POWERS has no edit or payment rights
- ABC TEST Portal not linked to AMANDA V7 Test
- Cant copy to Conditions field from Sharepoint Dashboard information. May be due to the screenshare
- Conditions field doesnt have the Infos in the drop down
![Conditions field Infos not available.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/43999348-2f2b-45f8-905d-25d912c162b7)

- All folders in all Groups Option not available and can cause conflict issues if they cant review the property list related to the folder
![Page Equivalent V7.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/93911bc6-48ff-4776-9737-5f3e111ef2cb)
![page equivalent on V6.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/973da59f-9b5e-4e3b-b6cc-1f6b1879fdf8)
![V6 All Folders Option.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/831f2e4b-35ab-4e24-8bfd-5d22b0d317f4)
![v6 all_pROPERTIES_History.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/746aa1d9-3d55-444d-9fc0-8ecf232dbec9)

- "Total days Validity" info field is not editable but is not needed for Film permit issuance. They would like for it to be removed
![Total Days Permit Validity.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/6ef3d953-f00c-4675-af86-f17f0793e208)

- "Event Review" Process after "Web Acceptance" is not needed, Prevents Issuance if not closed. 
![Event Review not needed.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/1adb8320-bdff-45f3-8c09-5284f1cb35bb)
- "Event Review" process, when "Accepted" gives same ORA SQL Error:
![ORA Error on Approved Event Review Film.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/f5019748-1977-489d-b0fa-64f707cca551)

> ORA-06592: CASE not found while executing CASE sattement
> ORA-06512: at "AMANDA.COA_FOLDER_FEES", line 546
> ORA-06512: at "AMANDA.DEFAULTFEE_RW_50141", line 8
> ORA-06512: at "AMANDA.PROCESS_RW_00050560", line 192
> ORA-06512: at "AMANDA.DEFAULTPROCESS_RW_00050560", line 5
> ORA-06512: at 1

- "Event Review" process, when "Accepted",  also adds fees a $2000 Arterial Fee that isnt needed
- SQL Email error from Print/Email option. Still received email
![SQL Email error.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/989bd685-04f5-49b4-9dd8-3ac61a243b65)

## **Main Concerns in Order of Importance:**
- All folders in all Groups Option not available and can cause conflict issues if they cant review the property list related to the folder
- "Event Review" Process after "Web Acceptance" is not needed, Prevents Issuance if not closed.
- "Event Review" process, when "Accepted",  also adds fees a $2000 Arterial Fee that isnt needed
- "Event Review" process, when "Accepted" gives same ORA SQL Error
- SQL Email error from Print/Email option. Still received email
- "Total days Validity" info field is not editable but is not needed for Film permit issuance. They would like for it to be removed
