### ISSUE TITLE
EPIC: EX Folder

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-AMANDA-V7#8]
*In Progress*
_Epic_

**UAT Resource(s)**
- Izzy

**Test Session Info:**
- [x] Scheduled
- Date/Time: 12/22/2020 @ 10:00am - 11:30am
- [x] UAT on V7
- [x] Update Card with Notes

**Comment by Nadin-Nader** [comment]
**Met with Izzy and we started the UAT of AMANDA V7. Below are the notes from the UAT:**
**EX Folder**
**Folder: 2020 168709 000 00 EX **
**RSN: 12581290**

- **More UAT Needed since some of the infos could not be Updated/tested under my profile/login/Group**
- Cannot Update existing infos under own profile and my own

![Cannot edit info.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/f6c44f95-94b9-444e-89dc-a3bfc8319b74)

- Conditions Field in the Folder tab does not have the drop down infos
- Property & Street Information tab Izzy had to click each row to edit it from the address to the segment that is getting the excavating done, this will slowdown workflow **Need to see if there can be a multi-select or have it pull the Street segment instead of House address**
- Could not save the selection changes made as it gave an error
   - Error in Property & Street Information:

> "Unknown exception: java.lang.NullPointerException." When trying to Save the Street Segment

Also looked at **Sub Type = Private Contractor**
Folder: 2020 166657 000 00
RSN: 12578943

**ECV Folder: 2020 112405 000 00**
**RSN: 12516681**

**Folder: 2020 168580 000 00**
**RSN: 12581158**

and Used;
**Folder: 2020 171579 000 00**
**RSN: 12584609**

- Right of Way Usage and other fees are correct
- Adjustments leave the fees Looking unpaid  ***They usually pay a $0 amount to pay the fee in order to Issue.  They still generate bill, adjust the amount and they still have to pay the invoice from the budget (Works Like DS Smart Housing)***
- Error saying that it has unpaid fees when making adjustment

![Property and Sement Error.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/3c4f452f-805a-4860-a63e-aebf288be5f8)![Property and Street Segment edit error.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/184fe695-9b58-4e85-bf77-7037cfc58415)

- Adjustment on fee tab has to be voided or cancelled or it gives the Unpaid Fees error
- No other New Issues with Private Contractors

## **Main Issues Found:**

- Cannot Update existing infos under own profile and my own
- Property & Street Information tab Izzy had to click each row to edit it from the address to the segment that is getting the excavating done, this will slowdown workflow. **Izzy would like to know if there can be a multi-select or have it pull the Street segment instead of House address??**
- Conditions Field in the Folder tab does not have the drop down infos
- Adjustments leave the fees Looking unpaid  (They usually pay a $0 amount to pay the fee in order to Issue.  They still generate bill, adjust the amount and they still have to pay the invoice from the budget (Works Like DS Smart Housing)) **Work around is to Void or Cancel the Adjustment and Bill**
 
## **Errors that popped up:**
Property & Segment Tab
"Unknown exception: java.lang.NullPointerException." When trying to Save the Street Segment

**Comment by Nadin-Nader** [comment]
@TracyLinder I spoke to Izzy and asked her to test out the conditions infos and she was able to edit them for the EX folder now. I think we can close this one too.
